os: Visual Studio 2015

environment:
  matrix:
   - channel: nightly
     target: x86_64-pc-windows-msvc
  WXWIN: C:\wxWidgets

install:
# install rust
 - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
 - rustup-init -yv --default-toolchain %channel% --default-host %target%
 - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
 - rustc -vV
 - cargo -vV
# build wx
 - appveyor DownloadFile https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.3/wxWidgets-3.1.3.zip -FileName wx.zip
 - ps: Expand-Archive -Path 'wx.zip' -DestinationPath $env:WXWIN
 - cd %WXWIN%\build\msw
 - ps: Start-Process "cmd.exe" "\c "\C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat\""
 - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x86'
 - nmake.exe -f makefile.vc BUILD=release

build: false

test_script:
 - cargo test --verbose
