os: Visual Studio 2015

environment:
  matrix:
   - channel: nightly
     target: x86_64-pc-windows-gnu
  WXWIN: C:\wxWidgets3.1.2

install:
# install rust
 - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
 - rustup-init -yv --default-toolchain %channel% --default-host %target%
 - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
 - rustc -vV
 - cargo -vV
# install wx
 - ps: mkdir -p $env:WXWIN
 - cd %WXWIN%
 - appveyor DownloadFile https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.3/wxMSW-3.1.3_gcc730_ReleaseDLL.7z -FileName wx-libs.7z
 - 7z e -y wx-libs.7z
 - del wx-libs.7z
 - appveyor DownloadFile https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.3/wxWidgets-3.1.3-headers.7z -FileName wx-include.7z
 - 7z e -y wx-include.7z
 - del wx-include.7z
 - ps: ls -al
 - cd %APPVEYOR_BUILD_FOLDER%
# build wx-config
 - git clone https://github.com/kowey/wx-config-win.git
 - cd wx-config-win
 - set PATH=C:\MinGW\bin;%PATH
 - mingw32-g++ wx-config-win.cpp -s -o wx-config.exe
 - set PATH=%PATH%;%cd%
 - cd %APPVEYOR_BUILD_FOLDER%
 - wx-config --version

build: false

test_script:
 - cargo test --verbose
