# Description of how to build this program using the Appveyor CI

# Use the Visual Studio 2015 disk image- is a good build of windows that comes with QT utilities
os: Visual Studio 2015

# Load the Rust stable toolchain and the MSVC toolchain - we'll add more later
environment:
  matrix:
    - channel: stable
      target: x86_64-pc-windows-gnu
  CC: mingw64-gcc

# Install the desired version of Rust and set up the path.
install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin;C:\MinGW\bin;C:\Qt\5.5\mingw492_32
  - rustc -vV
  - cargo -vV
  - rustfmt -vV

# Cargo test takes care of the build process, so we don't need a build phase
build: false

test_script:
  - rustfmt --check src/lib.rs
  - cargo test
