os: Visual Studio 2015

environment:
  matrix:
   - channel: nightly
     target: x86_64-pc-windows-gnu
  WXWIN: C:\wxWidgets

install:
# install rust
 - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
 - rustup-init -yv --default-toolchain %channel% --default-host %target%
 - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
 - rustc -vV
 - cargo -vV
# build wx
 - appveyor DownloadFile https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.3/wxWidgets-3.1.3.zip -FileName wx.zip
 - ps: Expand-Archive -Path 'wx.zip' -DestinationPath $env:WXWIN
 - cd %WXWIN%\build\msw
 - set PATH=C:\MinGW\bin;%PATH%
 - mingw32-make -j2 -f makefile.gcc BUILD=release CXXFLAGS="-std=gnu++11"

build: false

test_script:
 - cargo test --verbose
