os: Visual Studio 2015

environment:
  matrix:
   - channel: nightly
     target: x86_64-pc-windows-msvc
  WXWIN: C:\wxWidgets

install:
# install rust
 - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
 - rustup-init -yv --default-toolchain %channel% --default-host %target%
 - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
 - rustc -vV
 - cargo -vV
# build wx
 - appveyor DownloadFile https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.3/wxWidgets-3.1.3.7z -FileName wx.7z
 - 7z e wx.7z -y -o%WXWIN%
 - cd %WXWIN%\build\msw
 - C:\\Program Files\ \(x86\)\\Microsoft\ Visual\ Studio\ 14.0\\VC\\vcvarsall.bat
 - nmake.exe -f makefile.vc BUILD=release

build: false

test_script:
 - cargo test --verbose
