os: Visual Studio 2015

environment:
  matrix:
   - channel: nightly
     target: x86_64-pc-windows-gnu
  WXWIN: C:\wxWidgets

install:
# install rust
 - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
 - rustup-init -yv --default-toolchain %channel% --default-host %target%
 - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
 - rustc -vV
 - cargo -vV
# install wx
 - choco install wxwidgets
# build wx-config
 - git clone https://github.com/kowey/wx-config-win.git
 - cd wx-config-win
 - mingw32-g++ wx-config-win.cpp -s -o wx-config.exe
 - set PATH=%PATH%;%cd%
 - cd %APPVEYOR_BUILD_FOLDER%
 - wx-config --version

build: false

test_script:
 - cargo test --verbose
