os: Visual Studio 2015

environment:
  matrix:
   - channel: nightly
     target: x86_64-pc-windows-gnu
  WXWIN: C:\wxWidgets

install:
# install rust
 - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
 - rustup-init -yv --default-toolchain %channel% --default-host %target%
 - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
 - rustc -vV
 - cargo -vV
# build wx
 - choco install wxwidgets

build: false

test_script:
 - cargo test --verbose
