[package]
name = "tasinput2"
version = "0.1.2"
authors = ["not_a_seagull <jtnunley01@gmail.com>"]
edition = "2018"

[lib]
name = "tasinput2"
path = "src/lib.rs"
crate-type = ["staticlib", "cdylib"]

[dependencies]
thiserror = "1.0.9"
qt_widgets = "0.4.1"