[package]
name = "tasinput2"
version = "0.1.0"
authors = ["not_a_seagull <notaseagull048@gmail.com>"]
edition = "2018"

[lib]
name = "tasinput2"
crate-type = ["staticlib", "cdylib"]
path = "src/lib.rs"

[dependencies]

[build-dependencies]
cc = "1.0.50"
