[package]
name = "tasinput2"
version = "0.1.2"
authors = ["not_a_seagull <jtnunley01@gmail.com>"]
edition = "2018"

[lib]
name = "tasinput2"
path = "src/lib.rs"
crate-type = ["staticlib", "cdylib"]

[dependencies]
lazy_static = "1.4.0"
libc = "0.2.66"
qt_widgets = "0.4.1"
thiserror = "1.0.9"

[build-dependencies]
bindgen = "0.52.0"
futures = "0.3.1"
reqwest = { version = "0.10.1", features = ["json", "stream"] }
tempfile = "3.1.0"
tokio = { version = "0.2", features = ["full"] }
