name: build

on: [push, pull_request]

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: windows-latest
    steps:
     - uses: actions/checkout@master
     - name: Install Rust
       run: rustup update stable
     - name: Set Rust Default Toolchain
       run: rustup default stable
     - name: Install Rustfmt
       run: rustup component add rustfmt
     - run: cargo fmt -- --check
  
  test:
    name: Check
    runs-on: windows-latest
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    steps:
     - uses: actions/checkout@master
     - name: Install Rust
       run: rustup update ${{ matrix.toolchain }}
     - name: Set Rust Default Toolchain
       run: rustup default ${{ matrix.toolchain }}
     - name: Install Qt
       uses: jurplel/install-qt-action@v2
     - name: Install MSVC Build Tools
       uses: ilammy/msvc-dev-cmd@v1
     - run: cargo test

  deploy:
    needs: test
    runs-on: windows-latest
    steps:
     - uses: actions/checkout@master
     - name: Install Rust
       run: rustup update stable
     - name: Set Rust Default Toolchain
       run: rustup default stable
     - name: Install Qt
       uses: jurplel/install-qt-action@v2
     - name: Install MSVC Build Tools
       uses: ilammy/msvc-dev-cmd@v1
     - run: cargo build --release
