name: CI

on: [push, pull_request]

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@master
     - name: Install Rust
       run: rustup update stable && rustup default stable
     - name: Install Rustfmt
       run: rustup add component rustfmt
     - run: cargo fmt -- --check
  
  test:
    name: Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        toolchain: [stable, beta, nightly]
    steps:
     - uses: actions/checkout@master
     - name: Install Rust
       run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
     - run: cargo test
